version: "3"

services:
  db:
    image: postgis/postgis
    container_name: casitas-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exampledb
    ports:
      - 5432:5432

  back:
    container_name: "casitas-back"
    build: "./back/."
    expose:
      - 3000
    command: >
      sh -c "npx prisma db push --schema=./prisma/schema.prisma && npm run start:prod & wait"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/exampledb?schema=public
      - JWT_SECRET=this is my secret
    networks:
      - nginx_proxy_default
    depends_on:
      - db

  front:
    container_name: "casitas-front"
    build: "./front/."
    expose:
      - 80
    networks:
      - nginx_proxy_default

networks:
  nginx_proxy_default:
    external: true
